### ISSUE TITLE
No module named '_ext'

### ISSUE THREAD

**Issue by kashiani** [yuexy/PS-ViT#3]
Thank you for your awesome work. I have followed all steps for training your model; however, I encountered the following error which happens for importing your model in line 9 of main.py (`import models`). Although it seems that models have not been used anywhere in main.py, when I commented `import models`, another error would occur in line 315 in `create_model` of main.py. 

I would be grateful if you could guide me to deal with this issue. 

```
Traceback (most recent call last):
  File "/home/amir/Documents/PS-ViT/main.py", line 9, in <module>
    import models
  File "/home/amir/Documents/PS-ViT/models/_init_.py", line 1, in <module>
    from .ps_vit import *
  File "/home/amir/Documents/PS-ViT/models/ps_vit.py", line 4, in <module>
    from timm.models.helpers import load_pretrained
  File "/home/amir/anaconda3/envs/ps_vit/lib/python3.7/site-packages/timm/_init_.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/home/amir/anaconda3/envs/ps_vit/lib/python3.7/site-packages/timm/models/_init_.py", line 1, in <module>
    from .ps_vit import *
  File "/home/amir/anaconda3/envs/ps_vit/lib/python3.7/site-packages/timm/models/ps_vit.py", line 8, in <module>
    from layers import ProgressiveSample
  File "/home/amir/Documents/PS-ViT/layers/_init_.py", line 1, in <module>
    from .progressive_sample import ProgressiveSample
  File "/home/amir/Documents/PS-ViT/layers/progressive_sample.py", line 9, in <module>
    'progressive_sampling_backward'])
  File "/home/amir/Documents/PS-ViT/utils/ext_loader.py", line 5, in load_ext
    ext = importlib.import_module(name)
  File "/home/amir/anaconda3/envs/ps_vit/lib/python3.7/importlib/_init_.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_ext'

Process finished with exit code 1
```

**Comment by yuexy** [comment]
Please run `python setup.py build_ext --inplace` to compile C++ and CUDA code.
